# Combined training config: dataset + dataloader from default.yaml and model from pointnext-s_kdtree.yaml

num_points: 1024

# Dataset Related (from default.yaml)
dataset:
  common:
    NAME: ModelNet40Ply2048
    data_dir: './data/ModelNet40Ply2048'
  train:
    split: train
    num_points: 1024
  val:
    split: test
    num_points: 1024

feature_keys: pos

datatransforms:
  train: [PointsToTensor, PointCloudScaleAndTranslate]
  vote: [PointCloudScaleAndTranslate]
  val: [PointsToTensor]
  kwargs:
    shift: [0.2, 0.2, 0.2]

batch_size: 2
val_batch_size: 2

dataloader:
  num_workers: 0

num_classes: 40

# Model (from pointnext-s_kdtree.yaml)
model:
  NAME: BaseCls
  encoder_args:
    NAME: PointNextEncoder
    blocks: [1, 1, 1, 1, 1, 1]
    strides: [1, 2, 2, 2, 2, 1]
    width: 32
    in_channels: 3
    radius: 0.15
    radius_scaling: 1.5
    sa_layers: 2
    sa_use_res: True
    nsample: 32
    expansion: 4
    sampler: kdtree
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  cls_args:
    NAME: ClsHead
    num_classes: 40
    mlps: [512, 256]
    norm_args:
      norm: 'bn1d'
